force-app/main/default/objects/Application_Underwriting__c/Application_Underwriting__c.object-meta.xml
<CustomObject>
    <label>Application Underwriting</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>Application Underwriting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Underwriting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Underwriting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Application__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Applications__c</referenceTo>
    <relationshipLabel>Applications Underwriting</relationshipLabel>
    <relationshipName>Applications_Underwriting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>KYC Review</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Review</fullName>
            </value>
            <value>
                <fullName>Loan Docs Review</fullName>
            </value>
            <value>
                <fullName>Funding Docs Review</fullName>
            </value>
            <value>
                <fullName>Bank Statement Review</fullName>
            </value>
            <value>
                <fullName>FICO Review</fullName>
            </value>
            <value>
                <fullName>Asset Review</fullName>
            </value>
            <value>
                <fullName>Liabilities Review</fullName>
            </value>
            <value>
                <fullName>Collateral Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/Liability_Summary__c.object-meta.xml
<CustomObject>
    <label>Liability Summary</label>
    <nameField>
        <displayFormat>LB-{00000}</displayFormat>
        <label>Liability Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Liabilities Summary</relationshipLabel>
    <relationshipName>Liabilities_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Amount_Owing__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owing__c</fullName>
    <label>Amount Owing</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Application_Underwriting__c.field-meta.xml
<CustomField>
    <fullName>Application_Underwriting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Underwriting</label>
    <referenceTo>Application_Underwriting__c</referenceTo>
    <relationshipLabel>Liabilities Summary</relationshipLabel>
    <relationshipName>Liabilities_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Liability_Name__c.field-meta.xml
<CustomField>
    <fullName>Liability_Name__c</fullName>
    <label>Liability Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Liability_Type__c.field-meta.xml
<CustomField>
    <fullName>Liability_Type__c</fullName>
    <label>Liability Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Student Loan</fullName>
            </value>
            <value>
                <fullName>Credit Card Debt</fullName>
            </value>
            <value>
                <fullName>Notes Payable</fullName>
            </value>
            <value>
                <fullName>Real Estate/Mortgage</fullName>
            </value>
            <value>
                <fullName>Other Expenses</fullName>
            </value>
            <value>
                <fullName>Fed and State Tax</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>Utility Payments</fullName>
            </value>
            <value>
                <fullName>Family Expenses</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Stated_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>Stated_Net_Worth__c</fullName>
    <label>Stated Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Liability_Summary__c/fields/Total_Liabilities_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Liabilities_Amount__c</fullName>
    <label>Total Liabilities Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LiabilitiesSummary.cls
public with sharing class LiabilitiesSummary{
    @AuraEnabled(cacheable=true)
    public Static List<Liability_Summary__c> getLiabilitySummaryRecords(String recordid) {
        Set<Id> setOfConIds = new Set<Id>();
        Application_Underwriting__c appUnderwritingRecord = [SELECT Id,Stages__c,Application__c,RecordTypeId,RecordType.Name FROM Application_Underwriting__c WHERE Id =: recordid];
        Applications__c appRecord = [select id, Account__c, Account__r.Email__c from Applications__C where Id =: appUnderwritingRecord.Application__c];
        // List<Contact> conList = [SELECT Id,accountid FROM contact WHERE accountid =:appRecord.Account__c];
        // for(Contact conn : conList){
        //     setOfConIds.add(conn.Id);
        // }
        List<Liability_Summary__c> listOfAssetSummary = [SELECT Id,Name,Account__c,Liability_Name__c,Liability_Type__c,Original_Amount__c,Payment_Amount__c,Stated_Net_Worth__c,Total_Liabilities_Amount__c,Amount_Owing__c FROM Liability_Summary__c WHERE Account__c =: appRecord.Account__c];
        System.debug('#####'+listOfAssetSummary);
        return listOfAssetSummary;
    }
}