force-app/main/default/objects/Application_Underwriting__c/Application_Underwriting__c.object-meta.xml
<CustomObject>
    <label>Application Underwriting</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>Application Underwriting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Underwriting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Underwriting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Application__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Applications__c</referenceTo>
    <relationshipLabel>Applications Underwriting</relationshipLabel>
    <relationshipName>Applications_Underwriting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>KYC Review</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Review</fullName>
            </value>
            <value>
                <fullName>Loan Docs Review</fullName>
            </value>
            <value>
                <fullName>Funding Docs Review</fullName>
            </value>
            <value>
                <fullName>Bank Statement Review</fullName>
            </value>
            <value>
                <fullName>FICO Review</fullName>
            </value>
            <value>
                <fullName>Asset Review</fullName>
            </value>
            <value>
                <fullName>Liabilities Review</fullName>
            </value>
            <value>
                <fullName>Collateral Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/Asset_Summary__c.object-meta.xml
<CustomObject>
    <label>Asset Summary</label>
    <nameField>
        <displayFormat>ASS-{0000}</displayFormat>
        <label>Asset Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets Summary</relationshipLabel>
    <relationshipName>Assets_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/fields/Application_Underwriting__c.field-meta.xml
<CustomField>
    <fullName>Application_Underwriting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Underwriting</label>
    <referenceTo>Application_Underwriting__c</referenceTo>
    <relationshipLabel>Assets Summary</relationshipLabel>
    <relationshipName>Assets_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/fields/Asset_Description__c.field-meta.xml
<CustomField>
    <fullName>Asset_Description__c</fullName>
    <label>Asset Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cash-Savings</fullName>
            </value>
            <value>
                <fullName>Certificate of Deposits</fullName>
            </value>
            <value>
                <fullName>Notes and Contracts held</fullName>
            </value>
            <value>
                <fullName>Securities/Bonds</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Liquid Assets</fullName>
            </value>
            <value>
                <fullName>Securities</fullName>
            </value>
            <value>
                <fullName>Business Ownership</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Cash Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/fields/Market_Value_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Value_Date__c</fullName>
    <label>Market Value Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset_Summary__c/fields/Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Amount__c</fullName>
    <label>Original Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AssetSummaryController.cls
public with sharing class AssetSummaryController {
    @AuraEnabled(cacheable=true)
    public Static List<Asset_Summary__c> getAssetSummaryRecords(String recordid) {
        Set<Id> setOfConIds = new Set<Id>();
        Application_Underwriting__c appUnderwritingRecord = [SELECT Id,Stages__c,Application__c,RecordTypeId,RecordType.Name FROM Application_Underwriting__c WHERE Id =: recordid];
        Applications__c appRecord = [select id, Account__c, Account__r.Email__c from Applications__C where Id =: appUnderwritingRecord.Application__c];
        // List<Contact> conList = [SELECT Id,accountid FROM contact WHERE accountid =:appRecord.Account__c];
        // for(Contact conn : conList){
        //     setOfConIds.add(conn.Id);
        // }
        List<Asset_Summary__c> listOfAssetSummary = [SELECT Id,Name,Account__c,Account__r.Name,Account_Number__c,Asset_Description__c,Asset_Type__c,Institution_Name__c,Market_Value__c,Market_Value_Date__c,Original_Amount__c FROM Asset_Summary__c WHERE Account__c =: appRecord.Account__c];
        System.debug('#####'+listOfAssetSummary);
        return listOfAssetSummary;
    }
}