force-app/main/default/objects/Application_Underwriting__c/Application_Underwriting__c.object-meta.xml
<CustomObject>
    <label>Application Underwriting</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>Application Underwriting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications Underwriting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Underwriting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Application__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Applications__c</referenceTo>
    <relationshipLabel>Applications Underwriting</relationshipLabel>
    <relationshipName>Applications_Underwriting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Underwriting__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>KYC Review</fullName>
            </value>
            <value>
                <fullName>Borrower Entity Review</fullName>
            </value>
            <value>
                <fullName>Loan Docs Review</fullName>
            </value>
            <value>
                <fullName>Funding Docs Review</fullName>
            </value>
            <value>
                <fullName>Bank Statement Review</fullName>
            </value>
            <value>
                <fullName>FICO Review</fullName>
            </value>
            <value>
                <fullName>Asset Review</fullName>
            </value>
            <value>
                <fullName>Liabilities Review</fullName>
            </value>
            <value>
                <fullName>Collateral Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Summary__c/Credit_Summary__c.object-meta.xml
<CustomObject>
    <label>Credit Summary</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Credit Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Summary__c/fields/Application_Underwriting__c.field-meta.xml
<CustomField>
    <fullName>Application_Underwriting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Underwriting</label>
    <referenceTo>Application_Underwriting__c</referenceTo>
    <relationshipLabel>Credit Summaries</relationshipLabel>
    <relationshipName>Credit_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Summaries</relationshipLabel>
    <relationshipName>Credit_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Summary__c/fields/Credit_Score_Override_Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score_Override_Other_Reason__c</fullName>
    <label>Credit Score Override Other Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Summary__c/fields/Credit_Score_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score_Override_Reason__c</fullName>
    <label>Credit Score Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Level of Net Worth</fullName>
            </value>
            <value>
                <fullName>High Level of Liquidity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Summary__c/fields/Override_Min_Credit_Score_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Override_Min_Credit_Score_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Min Credit Score Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreditSummaryController.cls
public with sharing class CreditSummaryController {
    @AuraEnabled(cacheable=true)
    public Static List<Credit_Summary__c> getCreditSummaryRecords(String recordid) {
        Set<Id> setOfConIds = new Set<Id>();
        Application_Underwriting__c appUnderwritingRecord = [SELECT Id,Stages__c,Application__c,RecordTypeId,RecordType.Name FROM Application_Underwriting__c WHERE Id =: recordid];
        Applications__c appRecord = [select id, Account__c, Account__r.Email__c from Applications__C where Id =: appUnderwritingRecord.Application__c];
        List<Contact> conList = [SELECT Id,accountid FROM contact WHERE accountid =:appRecord.Account__c];
        for(Contact conn : conList){
            setOfConIds.add(conn.Id);
        }
        List<Credit_Summary__c> listOfCreditSummary = [SELECT Id,Name,Contact__c,Contact__r.Name,Credit_Score__c,Credit_Score_Override_Other_Reason__c,Credit_Score_Override_Reason__c,Override_Min_Credit_Score_Requirement__c FROM Credit_Summary__c WHERE Contact__c =: setOfConIds];
        System.debug('#####'+listOfCreditSummary);
        return listOfCreditSummary;
    }
}